# Generated by Django 3.1.3 on 2020-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201119_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(upload_to='profile_icons', verbose_name='アイコン'),
        ),
    ]
