# Generated by Django 3.1.3 on 2020-12-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201204_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.URLField(blank=True, verbose_name='アイコン(url)'),
        ),
    ]
