# Generated by Django 3.1.3 on 2020-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201206_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='アイコン(SNSから取得)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icons', verbose_name='アイコン'),
        ),
    ]
