# Generated by Django 3.1.3 on 2020-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_character_introduction'),
        ('users', '0011_auto_20201207_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faved_movies',
            field=models.ManyToManyField(blank=True, related_name='faved_users', through='users.FavedMovie', to='app.Movie', verbose_name='お気に入り映画'),
        ),
    ]
