# Generated by Django 3.1.3 on 2020-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField(blank=True)),
                ('screening_time', models.PositiveIntegerField(blank=True)),
                ('sumally', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('movie_icon', models.ImageField(blank=True, null=True, upload_to='movie-icons')),
            ],
        ),
    ]
