# Generated by Django 3.1.3 on 2020-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_moviecharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(through='app.MovieCategory', to='app.Movie', verbose_name='ひも付き映画'),
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(through='app.MovieCharacter', to='app.Movie', verbose_name='出演作品'),
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(through='app.MovieCategory', to='app.Category', verbose_name='楽しみ方'),
        ),
        migrations.AddField(
            model_name='movie',
            name='characters',
            field=models.ManyToManyField(through='app.MovieCharacter', to='app.Character', verbose_name='出演キャラ'),
        ),
    ]
