# Generated by Django 3.1.3 on 2020-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201117_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_icon',
            field=models.ImageField(blank=True, null=True, upload_to='movie_icons', verbose_name='作品アイコン'),
        ),
    ]
