# Generated by Django 3.1.3 on 2020-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201122_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='movies_categories', through='app.MovieCategory', to='app.Category', verbose_name='楽しみ方'),
        ),
    ]
