# Generated by Django 3.1.3 on 2020-12-15 02:53

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201126_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='movie',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort'),
        ),
    ]
