# Generated by Django 3.1.3 on 2020-12-15 03:03

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201215_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='No.'),
        ),
    ]
