# Generated by Django 3.1.3 on 2020-12-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.TextField(blank=True, verbose_name='予告編'),
        ),
    ]
