# Generated by Django 3.1.3 on 2020-12-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_character_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='asp_url_amazon_jp',
            field=models.TextField(blank=True, verbose_name='amazon_日本語'),
        ),
        migrations.AddField(
            model_name='movie',
            name='asp_url_amazon_us',
            field=models.TextField(blank=True, verbose_name='amazon_字幕版'),
        ),
    ]
