# Generated by Django 3.1.3 on 2021-01-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201229_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='キャッチコピー'),
        ),
    ]
