# Generated by Django 3.1.3 on 2021-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_character_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='subname',
            field=models.CharField(blank=True, max_length=150, verbose_name='サブネーム'),
        ),
    ]
